#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f "/run/apache2/httpd.pid"

# create missing directories
mkdir -p /run/apache2

# bind stdout/stdin
ln -sfT /dev/stderr /var/www/logs/error.log
# ln -sfT /dev/stdout /var/www/logs/access.log

# opcache defaults
echo "*/app/logs/*\n*/var/logs/*" > /etc/opcache.blacklist

# php config
export PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d

# Set web root
echo -e "\033[92mUsing \"/app/${WEBAPP_ROOT}\" as apache root directory!\033[0m"
sed -i "s#\"/app/\"#\"/app/${WEBAPP_ROOT}\"#" /etc/apache2/httpd.conf

exec httpd -DFOREGROUND
